spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/gt?useSSL=false&useServerPrepStmts=true&serverTimezone=UTC
    username: postgres
    password: postgres
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: demo.shr.pojo